Repository AmazingMech2418/ScratchCloud, pull requests merged in 2021-06, with the labels that each got.

#3 Remove requirement of cloud symbol
  README.md
  cloud.js
  package-lock.json
  package.json
Labels: enhancement

#9 Add Change By and Fix Minor Bugs
  cloud.js
  package-lock.json
  package.json
Labels: bug, enhancement, needs review

#12 Add `onload`
  cloud.js
  package-lock.json
  package.json
Labels: enhancement, needs review
